'use strict';
const $=id=>document.getElementById(id),money=n=>n.toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),num=(n,d=2)=>n.toLocaleString('pt-BR',{maximumFractionDigits:d}),pct=n=>num(n,2)+'%';
const labels={},defs={};let latest,announceTimer;const defaultState=Solace.defaults;
document.querySelector('.workspace').after($('method'));
function field(key,label,unit='',hint='',options=null){labels[key]=label;defs[key]={label,unit,hint,options};const value=defaultState[key];return `<div class="field" id="field-${key}"><label for="${key}">${label}</label>${options?`<select id="${key}" aria-describedby="hint-${key} error-${key}">${options.map(([v,l])=>`<option value="${v}" ${v===String(value)?'selected':''}>${l}</option>`).join('')}</select>`:`<div class="input-wrap"><input id="${key}" inputmode="decimal" type="text" value="${String(value).replace('.',',')}" autocomplete="off" aria-describedby="hint-${key} error-${key}">${unit?`<span class="suffix">${unit}</span>`:''}</div>`}<small id="hint-${key}">${hint}</small><span class="field-error" id="error-${key}"></span></div>`;}
const f=field,grid=(...items)=>`<div class="field-grid">${items.join('')}</div>`,sub=(title,content)=>`<h4>${title}</h4>${content}`;
$('batchField').innerHTML=f('batch','Velas no lote','un.','Unidades boas produzidas.');
const sections=[
['01','Cera & essência','Quantidades usadas em uma vela',
sub('Cera',grid(f('waxPrice','Preço da cera','R$','Valor da embalagem comprada.'),f('waxPack','Cera comprada (g)','g','Peso total da embalagem em gramas.'),f('waxUse','Cera por vela (g)','g','Peso da cera, sem a essência.')))+
sub('Essência',grid(f('oilPrice','Preço da essência','R$','Valor da embalagem comprada.'),f('oilPack','Essência comprada (g)','g','Peso total da embalagem em gramas.'),f('oilUse','Essência por vela (g)','g','Peso da essência usada em cada vela.')))+
sub('Perdas de insumos',grid(f('loss','Perda de cera e essência','%','Parcela comprada que se perde na produção.')))+'<p class="notice" id="fragranceNotice"></p>'],
['02','Pote & apresentação','Custos de cada vela pronta',grid(f('jar','Pote + tampa','R$'),f('wick','Pavio + ilhós','R$'),f('label','Rótulo / etiqueta','R$'),f('box','Caixa / embalagem','R$'),f('extra','Outros materiais por vela','R$','Corante, fita, adesivo ou decoração.'),f('inbound','Frete dos insumos do lote','R$','Somente a parte do frete atribuída a este lote.'))],
['03','Tempo & produção','Valorize seu trabalho e cubra a estrutura',
sub('Seu trabalho',grid(f('laborMinutes','Tempo ativo do lote','min','Tempo total de trabalho; não inclua cura ou espera sem trabalho.'),f('hourly','Valor da sua hora','R$','A remuneração do trabalho entra antes do lucro.')))+
sub('Energia do lote',grid(f('watts','Potência do equipamento','W'),f('energyMinutes','Equipamento ligado no lote','min'),f('kwh','Tarifa de energia','R$','Por kWh. Consulte sua conta.'),f('batchExtra','Outros custos do lote','R$','Limpeza, consumíveis e outros gastos.')))+
sub('Estrutura do negócio',grid(f('fixedMonthly','Despesas fixas mensais','R$','Parte destinada às velas: aluguel, internet, tributos fixos etc.'),f('monthlyUnits','Previsão de vendas por mês','un.','Velas vendidas por mês, para dividir as despesas.')))+'<p class="notice">Não repita nas despesas fixas a energia ou a remuneração já incluída acima.</p>'],
['04','Venda & preço','Taxas, impostos e custos por pedido',
grid(f('fee','Cartão / plataforma','%','Soma das taxas que incidem sobre a venda.'),f('tax','Impostos sobre a venda','%','Use sua alíquota efetiva. Exemplo inicia em 0%.'),f('commission','Comissão de venda','%'),f('rounding','Arredondar preço para cima','','',[['0.01','Centavo mais próximo'],['0.5','Múltiplo de R$ 0,50'],['1','Real inteiro'],['5','Múltiplo de R$ 5,00']]))+
sub('Custos por pedido',grid(f('orderFee','Taxa fixa por pedido','R$'),f('shipping','Frete pago por você','R$','Parcela não coberta pelo cliente.'),f('orderUnits','Velas por pedido','un.','Divide a taxa fixa e o frete entre as velas.')))]
];
$('sections').innerHTML=sections.map(([n,title,desc,html],i)=>`<details class="section" ${i===0?'open':''}><summary><span class="number">${n}</span><span><span class="summary-title">${title}</span><span class="summary-desc">${desc}</span></span></summary><div class="section-body">${html}</div></details>`).join('');
$('marginField').innerHTML=f('margin','Margem de lucro desejada','%');
$('simulationFields').innerHTML=f('customPrice','Seu preço de tabela','R$')+f('discount','Desconto oferecido','%');
function read(){return Object.fromEntries(Object.keys(defaultState).map(k=>[k,$(k).value]));}
function row(label,value,cls=''){return `<div class="${cls}"><dt>${label}</dt><dd>${money(value)}</dd></div>`;}
function update(edited=false){const raw=read();const result=Solace.calculate(raw);latest=result;
if(edited){$('exampleTag').textContent='Simulação personalizada • confira todos os custos';}
for(const key of Object.keys(defaultState)){const error=result.errors[key];$(key).setAttribute('aria-invalid',String(!!error));$('error-'+key).textContent=error||'';}
const errorKeys=Object.keys(result.errors);$('errorSummary').hidden=!errorKeys.length;$('validResults').hidden=false;document.querySelectorAll('.result-section').forEach(el=>{el.hidden=!!errorKeys.length&&!el.contains($('simulationFields'));});$('printButton').hidden=!!errorKeys.length;$('printButton').disabled=!!errorKeys.length;
document.querySelectorAll('[data-margin]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.margin)===Solace.parse(raw.margin));b.setAttribute('aria-pressed',String(Number(b.dataset.margin)===Solace.parse(raw.margin)));});
if(errorKeys.length){$('errorSummary').innerHTML='<strong>Confira os campos para calcular</strong>'+errorKeys.map(k=>`<a href="#${k}" data-error-key="${k}">${labels[k]}: ${result.errors[k]}</a>`).join('');$('simulationResult').textContent='Corrija os campos indicados para simular.';$('discountHint').textContent='';for(const k of ['price','mobilePrice','cost','profit'])$(k).textContent='—';$('priceCaption').textContent='Corrija os campos indicados para obter um preço válido.';$('fragranceNotice').textContent='Informe quantidades válidas em gramas para conferir a essência.';return;}
const r=result,d=r.d;$('price').textContent=money(r.price);$('mobilePrice').textContent=money(r.price);$('cost').textContent=money(r.cost);$('profit').textContent=money(r.profit);$('priceCaption').textContent=`Para ${pct(d.margin)} de margem, após todos os custos informados.`;$('actualMargin').textContent=pct(r.actualMargin)+' de margem real';
const salesFees=r.price*r.rate;
$('breakdown').innerHTML=row('Cera',r.wax)+row('Essência',r.oil)+row('Perdas de insumos',r.waste)+row('Pote, pavio e apresentação',r.packaging)+row('Seu trabalho',r.labor)+row('Energia',r.energy)+row('Frete de insumos + extras',r.productionExtra)+row('Despesas fixas rateadas',r.fixed)+row('Taxa fixa + frete do pedido',r.order)+row('Custo total por vela',r.cost,'total-row')+row('Taxas + impostos + comissão',salesFees)+row('Lucro estimado',r.profit,'total-row')+row('Preço mínimo (cobre os custos)',Math.ceil((r.floor-1e-10)*100)/100);
$('costBar').innerHTML=[[r.cost,'#b9a58e'],[salesFees,'#f1dcbc'],[r.profit,'#756044']].map(([v,color])=>`<span style="width:${Math.max(0,v/r.price*100)}%;background:${color}"></span>`).join('');
$('batchSummary').innerHTML=`<div><span>Custo de ${num(d.batch,0)} velas¹</span><strong>${money(r.batchCost)}</strong></div><div><span>Lucro se vender o lote</span><strong>${money(r.batchProfit)}</strong></div><div><span>Receita bruta do lote</span><strong>${money(r.price*d.batch)}</strong></div><div><span>Equilíbrio mensal²</span><strong>${r.breakEven===null?'Inviável':num(r.breakEven,0)+' velas'}</strong></div>`;
$('supplies').innerHTML=`<p>Cera: <strong>${num(r.waxBatch)} g</strong><br>Essência: <strong>${num(r.oilBatch)} g</strong><br>Potes e pavios: <strong>${num(d.batch,0)} de cada</strong></p><p class="small">As quantidades de cera e essência já incluem as perdas. Quantidades fracionadas; arredonde conforme a precisão da sua balança.</p><p class="small">¹ Inclui despesas fixas rateadas e custos previstos dos pedidos, além da produção.<br>² Quantidade para cobrir as despesas fixas informadas, vendendo por ${money(r.price)}, com esta combinação de produto e custos. Pode mudar em um catálogo com várias velas.</p>`;
$('scenarios').innerHTML=r.scenarios.map(s=>`<div class="scenario">${s.margin}%<strong>${s.price===null?'Inviável':money(s.price)}</strong></div>`).join('');
$('simulationResult').classList.toggle('negative',r.saleProfit<0);$('simulationResult').innerHTML=`<strong>${money(r.sale)} por vela</strong>${r.saleProfit<0?'Prejuízo':'Lucro'}: ${money(Math.abs(r.saleProfit))} · Margem: ${r.saleMargin===null?'não definida':pct(r.saleMargin)}<br>${r.saleMargin===null?'Preço zero não cobre os custos.':r.saleMargin+1e-8>=d.margin?'Sua meta de margem está atendida.':'A margem fica abaixo da sua meta.'}`;
$('discountHint').textContent=`Partindo do preço recomendado: até ${pct(r.targetDiscount)} de desconto preserva sua meta; até ${pct(r.maxDiscount)} cobre os custos com lucro zero no limite. Percentuais aproximados; confirme o valor no simulador.`;
const oilGrams=d.oilUse;
$('fragranceNotice').textContent=d.waxUse>0?`Essência: ${pct(oilGrams/d.waxUse*100)} sobre o peso da cera. Todas as quantidades são em gramas. Este é um cálculo da receita informada, não uma recomendação de concentração. Respeite o limite do fornecedor.`:'Informe a quantidade de cera em gramas para conferir a concentração da essência.';
clearTimeout(announceTimer);announceTimer=setTimeout(()=>{$('announce').textContent=`Preço recomendado ${money(r.price)}. Lucro por vela ${money(r.profit)}.`;},650);
}
document.addEventListener('input',e=>{if(e.target.id==='candleName')return;if(Object.hasOwn(defaultState,e.target.id))update(true);});document.addEventListener('change',e=>{if(e.target.tagName==='SELECT')update(true);});
document.querySelectorAll('[data-margin]').forEach(b=>b.addEventListener('click',()=>{$('margin').value=b.dataset.margin;update(true);}));
$('errorSummary').addEventListener('click',e=>{const link=e.target.closest('[data-error-key]');if(!link)return;e.preventDefault();const input=$(link.dataset.errorKey);const section=input.closest('details');if(section)section.open=true;input.focus();input.scrollIntoView({block:'center',behavior:'smooth'});});
$('reset').addEventListener('click',()=>{if(!confirm('Restaurar os valores de exemplo? Os valores digitados serão substituídos.'))return;for(const [k,v]of Object.entries(defaultState))$(k).value=typeof v==='number'?String(v).replace('.',','):v;$('candleName').value='Lavanda · coleção essencial';$('exampleTag').textContent='Valores de exemplo • ajuste à sua produção';update();});
$('helpButton').addEventListener('click',()=>{$('method').querySelector('details').open=true;$('method').scrollIntoView({behavior:'smooth'});});
let printDetails=[];window.addEventListener('beforeprint',()=>{printDetails=[...document.querySelectorAll('details')].map(el=>[el,el.open]);printDetails.forEach(([el])=>el.open=true);});window.addEventListener('afterprint',()=>printDetails.forEach(([el,open])=>el.open=open));$('printButton').addEventListener('click',()=>{document.title=($('candleName').value||'Minha vela')+' — Precificação Solace';window.print();});$('calculator').addEventListener('submit',e=>e.preventDefault());update();

